### ISSUE TITLE
[Bug] Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Secret.data.kcpassword

### ISSUE THREAD

**Issue by pichuang** [InfuseAI/primehub#107]
**What happened**:
Following the [installation guide](https://github.com/InfuseAI/primehub/blob/master/INSTALL.md#install) and it seems that there is no manifest in helm repository

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Secret.data.kcpassword

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Prepare the [primehub-values.yaml](https://gist.github.com/pichuang/c984aac99279b00350e095c37ec1ac9e)

```
$ helm repo add infuseai https://charts.infuseai.io
$ helm update
$ helm upgrade \
  primehub infuseai/primehub \
  --install \
  --create-namespace \
  --namespace hub  \
  --values primehub-values.yaml

coalesce.go:196: warning: cannot overwrite table with non table for extraEnv (map[])
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Secret.data.kcpassword
```

**Anything else we need to know?**:

**Environment**:
- PrimeHub version (use `helm ls`):
```
$ helm ls
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```

- Helm version
```
$ helm version
version.BuildInfo{Version:"v3.2.3+4.el8", GitCommit:"2160a65177049990d1b76efc67cb1a9fd21909b1", GitTreeState:"clean", GoVersion:"go1.13.4"}
```

- Kubernetes version (use `kubectl version`):
```
$ oc version
Client Version: openshift-clients-4.4.0-202005231254
Server Version: 4.3.13
Kubernetes Version: v1.16.2
```

- Cloud provider or hardware configuration:
```
OpenShift 4.3 on AWS 
```

- OS (e.g: `cat /etc/os-release`):
```
sh-4.4# cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="43.81.202004130853.0"
VERSION_ID="4.3"
OPENSHIFT_VERSION="4.3"
RHEL_VERSION=8.0
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 43.81.202004130853.0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.3"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.3"
OSTREE_VERSION='43.81.202004130853.0'
```

- Kernel (e.g. `uname -a`):
```
sh-4.4# uname -a
Linux ip-10-0-141-73 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Wed Feb 26 03:08:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hSATAC** [comment]
Hi @pichuang 

I believe this is related to helm v3

The latest release of PrimeHub CE (v2.7) supports helm 2

Would you mind try installing PrimeHub using helm v2?

We will be fixing this and migrated to helm v3 in the next release (PrimeHub CE v2.8)

It should be available in few days, you could also wait for the new release, thanks.

**Comment by pichuang** [comment]
Hi @hSATAC No problem. Please @ me when helm 3 is available.

**Comment by hSATAC** [comment]
@pichuang Thanks for your patience. PrimeHub CE v2.8 chart is released today. It supports helm 3 now.

You could also check out our installation example on https://www.katacoda.com/infuseai
