### ISSUE TITLE
Better way to inject jupyter_primehub.py

### ISSUE THREAD

**Issue by clkao** [InfuseAI/primehub#2]
Currently we need users to run helm with --set-file to inject jupyter_primehub.py.

See if subPath works for injecting jupyter_primehub.py.

Another option is to package the authenticator class

**Comment by clkao** [comment]
Currently we need users to run helm with --set-file to inject jupyter_primehub.py.

See if subPath works for injecting jupyter_primehub.py.

Another option is to package the authenticator class

**Comment by popcornylu** [comment]
How about inject the `jupyter_primehub.py` to `values.yaml` when publishing the chart?

pseudo code
```
import yaml

with open('values.yaml', mode='r') as valuefile:
    result = yaml.load(valuefile)

with open('jupyterhub_primehub.py', mode='r') as primehubfile:
    data = primehubfile.read()

result['jupyterhub']['hub']['extraConfig']['primehub'] = data
```
