### ISSUE TITLE
If helm delete and reinstall, it will use old secret.

### ISSUE THREAD

**Issue by popcornylu** [InfuseAI/primehub#22]
# Reproduce steps
1. helm upgrade --install
2. helm delete 
3. helm upgrade --install
4. go to hub page

# Current
1. Show 500
2. The client secret is wrong

# Expected
No error

# Note
The primehub-secret should be recreated after installation.

**Comment by clkao** [comment]
This is because of the dangling secret object in the namespace, right?  can we add something in the docs about teardown?  people should remove the whole namespace for now, as incomplete upgrade might also have dangling jobs preventing further upgrades from working.

**Comment by popcornylu** [comment]
May always reconstruct the secret for each installation. Will fix the `keycloak.url` mentioned in #19  issue as well.
