### ISSUE TITLE
[Bug] "nginx-ingress-ingress-nginx-controller" exceeded its progress deadline

### ISSUE THREAD

**Issue by hakanaku1234** [InfuseAI/primehub#359]
**What happened**:
can't install primehub CE (single node) 
i have encountered this problem:
# error: deployment "nginx-ingress-ingress-nginx-controller" exceeded its progress deadline

**What you expected to happen**:
see something like `[Require Action] Please relogin this session and run create singlenode again`

**How to reproduce it (as minimally and precisely as possible)**:
```sh
curl -O https://storage.googleapis.com/primehub-release/bin/primehub-install
chmod +x primehub-install
./primehub-install create singlenode
```

**Anything else we need to know?**:

**Environment**: ubuntu20.04 (in vmware)
- PrimeHub version (use `helm ls`):
- Kubernetes version (use `kubectl version`):
```json
{
  "clientVersion": {
    "major": "1",
    "minor": "21",
    "gitVersion": "v1.21.2",
    "gitCommit": "092fbfbf53427de67cac1e9fa54aaa09a28371d7",
    "gitTreeState": "clean",
    "buildDate": "2021-06-16T12:59:11Z",
    "goVersion": "go1.16.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "20+",
    "gitVersion": "v1.20.7-34+984a1cd176537e",
    "gitCommit": "984a1cd176537e2d36d7db36e49e787e1c42a0aa",
    "gitTreeState": "clean",
    "buildDate": "2021-06-11T05:08:05Z",
    "goVersion": "go1.15.13",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
`Linux ub 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by kentwelcome** [comment]
You just need to reopen your terminal session and run `./primehub-install create singlenode` again.
It's due to microk8s by default require admin privilege. We just add the current user to the group and gain access to the microk8s. 
Ref: https://microk8s.io/docs
