### ISSUE TITLE
How to Access the Portal Interface After I have installed all

### ISSUE THREAD

**Issue by VincentWei2021** [InfuseAI/primehub#508]
hub             hub-7986bdc7-ddgsg                                1/1     Running     0          49m
hub             keycloak-0                                        1/1     Running     1          49m
hub             keycloak-postgres-0                               1/1     Running     0          49m
hub             metacontroller-0                                  1/1     Running     0          49m
hub             primehub-admission-77ffb567ff-kzpgr               1/1     Running     0          49m
hub             primehub-bootstrap-wmt4g                          0/1     Completed   0          49m
hub             primehub-console-755b6c4d49-whbc4                 1/1     Running     0          49m
hub             primehub-controller-747dddc4d6-72tb9              2/2     Running     0          49m
hub             primehub-graphql-79dbcb47ff-8ck25                 1/1     Running     3          49m
hub             primehub-metacontroller-webhook-7ffb6dffb-lgs6r   1/1     Running     0          49m
hub             primehub-watcher-7d789bd6b6-45twj                 1/1     Running     0          49m
hub             proxy-6677bcf9cf-5j6nv                            1/1     Running     0          49m
ingress-nginx   ingress-nginx-admission-create-q8tdj              0/1     Completed   0          39h
ingress-nginx   ingress-nginx-admission-patch-nj6tf               0/1     Completed   2          39h
ingress-nginx   ingress-nginx-controller-dl5gr                    1/1     Running     1          39h
jupyter         continuous-image-puller-m4vbk                     1/1     Running     1          23h
jupyter         hub-74dfcd4b48-6b5p8                              1/1     Running     1          23h
jupyter         proxy-74487c9bd-r98qq                             1/1     Running     1          23h
jupyter         user-scheduler-7b4594f97c-dj8ts                   1/1     Running     2          23h
jupyter         user-scheduler-7b4594f97c-mnxsh                   1/1     Running     1          23h
kube-system     coredns-57d4cbf879-92gdw                          1/1     Running     1          47h
kube-system     coredns-57d4cbf879-jz5wh                          1/1     Running     1          26h
kube-system     etcd-k8s-master                                   1/1     Running     3          47h
kube-system     kube-apiserver-k8s-master                         1/1     Running     5          47h
kube-system     kube-controller-manager-k8s-master                1/1     Running     2          25h
kube-system     kube-proxy-b7zgh                                  1/1     Running     0          47h
kube-system     kube-scheduler-k8s-master                         1/1     Running     2          25h
kuboard         kuboard-agent-2-84fb67bf67-6pb58                  1/1     Running     4          43h
kuboard         kuboard-agent-7fb4dffc4f-rhnl6                    1/1     Running     1          43h
kuboard         kuboard-agent-mi7gb5-2-78b8b4846-l6zw6            1/1     Running     3          43h
kuboard         kuboard-agent-mi7gb5-5b58c6d688-2xq9k             1/1     Running     4          43h
kuboard         kuboard-etcd-vkbcq                                1/1     Running     0          43h
kuboard         kuboard-questdb-54c5bb79b8-mjtdp                  1/1     Running     1          43h
kuboard         kuboard-v3-5fc46b5557-7vrxv                       1/1     Running     1          43h

**Comment by gblpedia** [comment]
Hi @VincentWei2021 

The URL of the portal is the `PRIMEHUB_DOMAIN` you fill in during the installation progress.

**Comment by VincentWei2021** [comment]
But I can not open it, what's the port? So I can access by url:port

**Comment by gblpedia** [comment]
It is port 80 by default. what message is shown on your browser when accessing the domain?

And also, may I know information below:

- PrimeHub version (use `helm ls`)
- Kubernetes version (use `kubectl version`)
- Cloud provider or hardware configuration if any
- OS (e.g: `cat /etc/os-release`)

Thanks

**Comment by poga** [comment]
@VincentWei2021 You can lookup your PrimeHub instance's login URL in the CloudFormation output

![Screen_Shot_2021-09-03_at_20 43 15](https://user-images.githubusercontent.com/8631/132173090-cef8f779-6ae1-4640-95bc-a05db446e4da.png)

**Comment by VincentWei2021** [comment]
hub             hub-544454f98f-dffmd                                      1/1     Running     0          48m  
hub             keycloak-0                                                1/1     Running     0          48m  
hub             keycloak-postgres-0                                       1/1     Running     0          48m  
hub             metacontroller-0                                          1/1     Running     0          48m  
hub             primehub-admission-77ffb567ff-ckdf9                       1/1     Running     0          48m  
hub             primehub-bootstrap-ktjz7                                  0/1     Completed   0          48m  
hub             primehub-console-755b6c4d49-z572g                         1/1     Running     0          48m  
hub             primehub-controller-747dddc4d6-c9nk5                      2/2     Running     0          48m  
hub             primehub-graphql-9ccd5b96-jvd8c                           1/1     Running     0          48m  
hub             primehub-metacontroller-webhook-7ffb6dffb-5hzdg           1/1     Running     0          48m  
hub             primehub-watcher-7d789bd6b6-cqhp5                         1/1     Running     0          48m  
hub             proxy-7b6cd9749b-h9x2n                                    1/1     Running     0          48m 
------------------------------------------------------------------------------------------------------------
primehub-3.7.2
----------------------------------------
kubenetes 1.20.1
------------------------------
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
--------------------------------------------------------
CE  singlenode

**Comment by VincentWei2021** [comment]
I guess the nginx ingress may be the problem
I edit svc primehub-console. append externalIPs, but I also cannot access through external ip

**Comment by VincentWei2021** [comment]
Sorry, I got it,  I install Cloud Edition locally!! what the hell........
