### ISSUE TITLE
[Bug] INSTALLATION FAILED: chart requires kubeVersion: >=1.19.0-0 which is incompatible with Kubernetes v1.16.15

### ISSUE THREAD

**Issue by huang06** [InfuseAI/primehub#604]
**What happened**:

I follow this [instruction](https://docs.primehub.io/docs/getting_started/prerequisites#kubernetes-cluster-116) to install the K8s v1.16.15 on my workstation. 

But during the installation of **ingress-nginx/ingress-nginx**, it warns that it requires kubeVersion >= 1.19

```bash
Error: INSTALLATION FAILED: chart requires kubeVersion: >=1.19.0-0 which is incompatible with Kubernetes v1.16.15
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ helm install nginx-ingress ingress-nginx/ingress-nginx --create-namespace --namespace ingress-nginx --set controller.hostNetwork=true --set rbac.create=true

Error: INSTALLATION FAILED: chart requires kubeVersion: >=1.19.0-0 which is incompatible with Kubernetes v1.16.15
```

**Anything else we need to know?**:

**Environment**:
- PrimeHub version (use `helm ls`):
- Kubernetes version (use `kubectl version`): v1.16.15
- Cloud provider or hardware configuration: on-premise
- OS (e.g: `cat /etc/os-release`): Ubuntu Server 20.04.3
- Kernel (e.g. `uname -a`):  5.4.0-89-generic

**Comment by DaveFlynn** [comment]
Hi huang06,

Thanks for bringing this outdated documentation to our attention. Apologies for any wasted time!

We are current updating the docs with the current preferred versions. Please retry the install with the following versions:

Kubernetes 1.21
Helm 3.6.2

Thanks

Dave

**Comment by DaveFlynn** [comment]
To continue installing on K8s 1.16 you could also specify the version of nginx-ingress by using the `--version` flag:

`helm install nginx-ingress ingress-nginx/ingress-nginx --create-namespace --namespace ingress-nginx --set controller.hostNetwork=true --set rbac.create=true \
--version 3.36.0`
