### ISSUE TITLE
support for k8s v1.22 v1.23

### ISSUE THREAD

**Issue by ziyi-bear** [InfuseAI/primehub#645]
**What would you like to be added**:  support for k8s version v1.22 v1.23

**Why is this needed**: Error: failed to install CRD crds/metacontroller/crd.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

**Comment by DaveFlynn** [comment]
Hi ziyi-bear,

Thanks for your message. 

Currently support for up to k8s version 1.23 is expected to happen towards the end of Q1 2022.

Please check back next year.

Dave

**Comment by tianlinzx** [comment]
Any updates on this ?
