### ISSUE TITLE
[Bug] one-click version of the README badge differs from https://one.primehub.io/

### ISSUE THREAD

**Issue by tai271828** [InfuseAI/primehub#659]
**What happened**:
The link of the badge: v1.1.3 starter
The link from the official site: v.1.1.4 https://one.primehub.io/

**What you expected to happen**:
- By using the one-click badge I can build a stack that allows me to deploy at least one model.
- By using the one-click badge I can select `ee` on building the stack.

**How to reproduce it (as minimally and precisely as possible)**:
- Click the badge from this repository and the official site.
- After building the stack, go to the `Deployment` tab of your PrimeHub console.

**Anything else we need to know?**:
Actual result: v1.1.3 (the badge of this repository) only provides `ce` and (of course) does not allow us to deploy models.

**Comment by DaveFlynn** [comment]
@tai271828  Thanks for bringing this to our attention. I have notified the developer team.
