### ISSUE TITLE
how can I deploy the primehub in an Ubuntu environment?

### ISSUE THREAD

**Issue by jojogh** [InfuseAI/primehub#677]
Is there anyway I can deploy the primehub in a native ubuntu env? Many thanks!

**Comment by hlb** [comment]
@jojogh sure, if you want to install PrimeHub community edition in a single Ubuntu machine, you can follow this doc. This will help you to install MicroK8s, our dependencies, and PrimeHub.

    https://docs.primehub.io/docs/getting_started/kubernetes_on_ubuntu_ce

If you want to install PrimeHub in a k8s cluster, please check our prerequisites and install doc:

    https://docs.primehub.io/docs/getting_started/prerequisites

**Comment by jojogh** [comment]
thanks, will try!
