### ISSUE TITLE
Add PrimeHub Python SDK examples into primehub-examples

### ISSUE THREAD

**Issue by LiuYuWei** [InfuseAI/primehub#684]
**What would you like to be added**:

Add PrimeHub Python SDK related Jupyter notebooks into primeHub-examples folder.

**Why is this needed**:

Users can learn how to use PrimeHub Python SDK & CLI to interact with PrimeHub.

**Comment by hlb** [comment]
new examples are in https://github.com/InfuseAI/primehub-examples
