### ISSUE TITLE
secret "primehub-client-admin-ui" or  "primehub-client-jupyterhub" not found

### ISSUE THREAD

**Issue by yuanbw** [InfuseAI/primehub#81]
**What happened**:
I followed the steps given on the official website,  and set the following variables：
PRIMEHUB_DOMAIN=test.corp.com.cn
PRIMEHUB_PASSWORD=password
KEYCLOAK_DOMAIN=test.corp.com.cn
KEYCLOAK_PASSWORD=password
STORAGE_CLASS=k8s-rbd
GRAPHQL_SECRET_KEY=$(openssl rand -hex 32)s
HUB_AUTH_STATE_CRYPTO_KEY=$(openssl rand -hex 32)
HUB_PROXY_SECRET_TOKEN=$(openssl rand -hex 32)

and then install it using helm:
helm upgrade \
--install \
--reset-values \
--namespace hub  \
--values primehub-values.yaml \
--timeout 3000 \
primehub infuseai/primehub

however, it reported errors after installation 

# kubectl get all -n hub
NAME                                                READY     STATUS                       RESTARTS   AGE
pod/admission-post-install-job-d77m5                0/1       Completed                    0          4m25s
pod/hub-6d56565db7-rq557                            0/1       CreateContainerConfigError   0          4m28s
pod/pod-image-replacing-webhook-b64ff775b-jdcs4     1/1       Running                      0          4m28s
pod/primehub-bootstrap-4h8tz                        1/1       Running                      0          4m19s
pod/primehub-console-7865c5cb89-r4tpd               0/1       CreateContainerConfigError   0          4m27s
pod/primehub-graphql-796596c56f-tj5sl               0/1       CreateContainerConfigError   0          4m28s
pod/primehub-group-7c4669f57f-8tqww                 1/1       Running                      0          4m28s
pod/primehub-watcher-fbd4cbc96-wwdxc                0/1       CreateContainerConfigError   0          4m28s
pod/proxy-6dfd9b946-fgvt2                           1/1       Running                      0          4m28s
pod/resources-validation-webhook-67755979f7-jrz22   1/1       Running                      0          4m27s

NAME                                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/hub                                ClusterIP   10.43.196.87    <none>        8081/TCP   4m28s
service/pod-image-replacing-webhook-svc    ClusterIP   10.43.235.106   <none>        443/TCP    4m28s
service/primehub-console                   ClusterIP   10.43.11.61     <none>        80/TCP     4m28s
service/primehub-graphql                   ClusterIP   10.43.129.79    <none>        80/TCP     4m28s
service/primehub-group                     ClusterIP   10.43.45.241    <none>        80/TCP     4m28s
service/proxy-api                          ClusterIP   10.43.191.100   <none>        8001/TCP   4m28s
service/proxy-public                       ClusterIP   10.43.195.14    <none>        80/TCP     4m28s
service/resources-validation-webhook-svc   ClusterIP   10.43.121.126   <none>        443/TCP    4m28s

NAME                                           READY     UP-TO-DATE   AVAILABLE   AGE
deployment.apps/hub                            0/1       1            0           4m28s
deployment.apps/pod-image-replacing-webhook    1/1       1            1           4m28s
deployment.apps/primehub-console               0/1       1            0           4m28s
deployment.apps/primehub-graphql               0/1       1            0           4m28s
deployment.apps/primehub-group                 1/1       1            1           4m28s
deployment.apps/primehub-watcher               0/1       1            0           4m28s
deployment.apps/proxy                          1/1       1            1           4m28s
deployment.apps/resources-validation-webhook   1/1       1            1           4m28s

NAME                                                      DESIRED   CURRENT   READY     AGE
replicaset.apps/hub-6d56565db7                            1         1         0         4m28s
replicaset.apps/pod-image-replacing-webhook-b64ff775b     1         1         1         4m28s
replicaset.apps/primehub-console-7865c5cb89               1         1         0         4m27s
replicaset.apps/primehub-graphql-796596c56f               1         1         0         4m28s
replicaset.apps/primehub-group-7c4669f57f                 1         1         1         4m28s
replicaset.apps/primehub-watcher-fbd4cbc96                1         1         0         4m28s
replicaset.apps/proxy-6dfd9b946                           1         1         1         4m28s
replicaset.apps/resources-validation-webhook-67755979f7   1         1         1         4m27s

NAME                                READY     AGE
statefulset.apps/user-placeholder   0/0       4m28s

NAME                                   COMPLETIONS   DURATION   AGE
job.batch/admission-post-install-job   1/1           4s         4m25s
job.batch/primehub-bootstrap           0/1           4m19s      4m19s

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

kubectl describe pod primehub-watcher-fbd4cbc96-wwdxc   -n hub, it returned that :
Events:
  Type     Reason     Age               From                        Message
  ----     ------     ----              ----                        -------
  Normal   Scheduled  7m                default-scheduler           Successfully assigned hub/primehub-watcher-fbd4cbc96-wwdxc to shoya15plpegpu087
  Normal   Pulling    7m                kubelet, shoya15plpegpu087  Pulling image "infuseai/primehub-console-watcher:bc0adf0"
  Normal   Pulled     7m                kubelet, shoya15plpegpu087  Successfully pulled image "infuseai/primehub-console-watcher:bc0adf0"
  Warning  Failed     5m (x12 over 7m)  kubelet, shoya15plpegpu087  Error: secret "primehub-client-admin-ui" not found
  Normal   Pulled     2m (x24 over 7m)  kubelet, shoya15plpegpu087  Container image "infuseai/primehub-console-watcher:bc0adf0" already present on machine

or returned like this:
Error: secret "primehub-client-jupyterhub" not found

**Environment**:
- PrimeHub version (use `helm ls`): 2.7
- Kubernetes version (use `kubectl version`): 1.15

I want to know if there is something wrong with my installation steps？

**Comment by hSATAC** [comment]
@yuanbw the pod `pod/primehub-bootstrap-4h8tz` should create those secret for you.

If bootstrap is not completed after a while, there might be something wrong when executing the boostrap script.
Would you please provide the logs of `pod/primehub-bootstrap-4h8tz`? Thanks.

**Comment by yuanbw** [comment]
Hi Ash，
the log for the&nbsp;pod/primehub-bootstrap-4h8tz is only:
# kubectl logs -f primehub-bootstrap-7zwb9 -n hub
Wait for keycloak ready...




Acctually, the&nbsp;keycloak is running fine, and i can&nbsp;enter&nbsp;Administrator Console&nbsp;and log in by the username and password.&nbsp;



[root@shoyvlpans01 prime]# kubectl -n default rollout status sts/keycloak


statefulset rolling update complete 1 pods at revision keycloak-5b79f8b8fb...
[root@shoyvlpans01 prime]#&nbsp;
[root@shoyvlpans01 prime]# kubectl -n default get pods
NAME &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; READY &nbsp; &nbsp; STATUS &nbsp; &nbsp;RESTARTS &nbsp; AGE
keycloak-0 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1/1 &nbsp; &nbsp; &nbsp; Running &nbsp; 0 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;19h





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ash Wu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月6日(星期一) 中午11:05
收件人:&nbsp;"InfuseAI/primehub"<primehub@noreply.github.com&gt;;
抄送:&nbsp;"袁博文"<76034183@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [InfuseAI/primehub] secret "primehub-client-admin-ui" or  "primehub-client-jupyterhub" not found (#81)





 
@yuanbw the pod pod/primehub-bootstrap-4h8tz should create those secret for you.
 
If bootstrap is not completed after a while, there might be something wrong when executing the boostrap script.
 Would you please provide the logs of pod/primehub-bootstrap-4h8tz? Thanks.

**Comment by hSATAC** [comment]
Looks like the boostrap script is having trouble connecting to keycloak.
Do you mind check the value of `KC_URL` env variable of the bootstrap pod, and make sure if it's reachable inside your Kubernetes pod? Thanks.

**Comment by yuanbw** [comment]
@hSATAC  I think the issue may be related with the https config of keycloak.

**After trying these commands to disable https in keycloak:**
#kubectl exec -it keycloak-0 /bin/sh
sh-4.4$ ./kcadm.sh config credentials \
>    --server http://localhost:8080/auth \
>    --realm master \
>    --user keycloak \
>    --password=password            
Logging into http://localhost:8080/auth as user keycloak of realm master
sh-4.4$ ./kcadm.sh update realms/master -s "sslRequired=none"
sh-4.4$ pwd 
/opt/jboss/keycloak/bin

**the bootstrap pod still wait keycloak ready:**
# kubectl logs  primehub-bootstrap-hnmrn  -n hub
Wait for keycloak ready...


 #kubectl exec -it primehub-bootstrap-hnmrn  -n hub /bin/sh
/ # curl  https://test.corp.com.cn/auth
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
/ # curl  https://test.corp.com.cn/auth -k -v
*   Trying 10.126.146.8:443...
* TCP_NODELAY set
* Connected to ml.prod.mlcloud.mcd.com.cn (10.126.146.8) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  start date: Jun 24 10:22:41 2020 GMT
*  expire date: Jun 24 10:22:41 2021 GMT
*  issuer: O=Acme Co; CN=Kubernetes Ingress Controller Fake Certificate
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55925f34dfa0)
> GET /auth HTTP/2
> Host: ml.prod.mlcloud.mcd.com.cn
> User-Agent: curl/7.66.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 303 
< server: nginx/1.17.10
< date: Tue, 07 Jul 2020 07:24:23 GMT
< content-length: 0
< location: https://test.corp.com.cn/auth/
< strict-transport-security: max-age=15724800; includeSubDomains
< 
* Connection #0 to host ml.prod.mlcloud.mcd.com.cn left intact
/ #

**Comment by qrtt1** [comment]
@yuanbw  could you provide the content of `primehub-values.yaml`

**Comment by yuanbw** [comment]
@qrtt1 
[root@shoyvlpans01 hub]# cat primehub-values.sh 
PRIMEHUB_DOMAIN=test.corp.com.cn
PRIMEHUB_PASSWORD=password
KEYCLOAK_DOMAIN=test.corp.com.cn
KEYCLOAK_PASSWORD=password
STORAGE_CLASS=k8s-rbd
GRAPHQL_SECRET_KEY=$(openssl rand -hex 32)s
HUB_AUTH_STATE_CRYPTO_KEY=$(openssl rand -hex 32)
HUB_PROXY_SECRET_TOKEN=$(openssl rand -hex 32)
cat <<EOF > primehub-values.yaml
primehub:
  scheme: https
  domain: ${PRIMEHUB_DOMAIN}
  keycloak:
    scheme: https
    domain: ${KEYCLOAK_DOMAIN}
    username: keycloak
    password: ${KEYCLOAK_PASSWORD}
bootstrap:
  usernmae: phadmin  
  password: ${PRIMEHUB_PASSWORD}
graphql:
  sharedGraphqlSecret: ${GRAPHQL_SECRET_KEY}
groupvolume:
  storageClass: ${STORAGE_CLASS}
ingress:
  hosts:
  -  ${PRIMEHUB_DOMAIN}
jupyterhub:
  auth:
    state:
      cryptoKey: ${GRAPHQL_SECRET_KEY}
  hub:
    db:
      pvc:
        storageClassName: ${STORAGE_CLASS}
  proxy:
    secretToken: ${HUB_PROXY_SECRET_TOKEN}
  singleuser:
    storage:
      dynamic:
        storageClass: ${STORAGE_CLASS}
EOF


[root@shoyvlpans01 hub]# cat primehub-values.yaml 
primehub:
  scheme: https
  domain: test.corp.com.cn
  keycloak:
    scheme: https
    domain: test.corp.com.cn
    username: keycloak
    password: password
bootstrap:
  usernmae: phadmin  
  password: password
graphql:
  sharedGraphqlSecret: 5040ee48c3f77fd8154935f3deafda904ef58fe5c5515d19668448474baf610ds
groupvolume:
  storageClass: k8s-rbd
ingress:
  hosts:
  -  test.corp.com.cn
jupyterhub:
  auth:
    state:
      cryptoKey: 5040ee48c3f77fd8154935f3deafda904ef58fe5c5515d19668448474baf610ds
  hub:
    db:
      pvc:
        storageClassName: k8s-rbd
  proxy:
    secretToken: 696c849c7a523166c1abad4c08f49f2442f63723dd6347aacaa860e2c3e349fb
  singleuser:
    storage:
      dynamic:
        storageClass: k8s-rbd

**Comment by aar0nTw** [comment]
```
primehub:
scheme: https
domain: ${PRIMEHUB_DOMAIN}
keycloak:
scheme: https
```
Hi @yuanbw could u try use `http` for `primehub.schema` and `keycloak.scheme` first, thanks.

and the `GRAPHQL_SECRET_KEY=$(openssl rand -hex 32)s` got an additional `s`, probably will get potential problem, pls remove the `s` character at end of line.

ref: https://github.com/InfuseAI/primehub/blob/master/INSTALL.md

**Comment by yuanbw** [comment]
@aar0nTw  thank you for your suggestions.It works now! 
Besides set the primehub.schema and keycloak.scheme to http,  i manully set the  the "Frontend URL" to http://test.corp.com.cn/auth in the keycloak console to make sure that it can be  reached from the primehub-bootstrap pod.
